version: '3'

services:
  awscli:
    build: 
      context: .
      dockerfile: Dockerfile.AwsCli
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  minio:
    build: 
      context: .
      dockerfile: Dockerfile.Minio
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
